### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by cuihantao** [anderson-optimization/em-psse#1]
First of all, thanks for open-sourcing this neat package for parsing PSSE raw data. 

I'm a researcher working on cyber-physical power system simulation. Recently I'm working on a major update for my open source simulator, [ANDES](https://github.com/cuihantao/andes). I may include your code for PSSE RAW parsing and possibly extend it to DYR files, if license permits. 

Therefore, adding a LICENSE file would be helpful.

**Comment by eanderson4** [comment]
Yah I can do that.  Do you have a preference on what license would be acceptable?  I probably can just do MIT.  I'm glad your able to find a use for this!

**Comment by cuihantao** [comment]
Perfect! I'm undecided between Apache and GPL v3. But either way, yours in MIT would work.

In fact, your work is very nice and easy to modify. I was quite impressed with the well-documented data format in your yaml file. 

Later, I will need to add a parser for PSSE dyr files. Since it's not tabulated and has a termination flag `/`, it can be parsed into data frames, one for each model, with optional headers from a yaml file.

I will keep you posted. Also let me know if you have any idea. Thank you!

**Comment by eanderson4** [comment]
Added.  

Let me know if you need anything, looks like your up to some cool stuff!

**Comment by eanderson4** [comment]
Are the dyr files used for your time-domain simulations, or what info do they have and what is their main purpose?

**Comment by cuihantao** [comment]
Sorry for the delay. The dyr file contains parameters for dynamic models and will be used for time-domain simulation (and also eigenvalue analysis).

Attached is an example dyr file. 
[IEEE39bus_3AC.dyr.zip](https://github.com/anderson-optimization/em-psse/files/3989887/IEEE39bus_3AC.dyr.zip)

**Comment by andersonopt** [comment]
Thanks for the sample.  It wouldn't hurt to add some tests to this library at some point and also try to support other formats. Feel free to submit any improvements as pull request.

Also, if want to add your software to this list of  [power analysis](https://github.com/anderson-optimization/awesome-power-analysis) that would be great.  I don't really know the time domain simulation area that well so maybe you could add a new section and include your package as well as others you know about.  

Closing this issue.  Let me know if anything else comes up.

**Comment by cuihantao** [comment]
Awesome. I will do that.
